### ISSUE TITLE
Runing index.py with Python 3.8

### ISSUE THREAD

**Issue by Uss-Momas** [JefferMarcelino/kabum-experiments#2]
When I was trying to run the file, an exception was raised:
`Traceback (most recent call last):
  File "index.py", line 117, in <module>
    main()
  File `"index.py",` line 113, in main
    generate_mentions_rank_json(posts, "entity_rank.json")
  File "index.py", line 54, in generate_mentions_rank_json
    nlp = spacy.load("pt_core_news_lg")
 File "/home/name/contributing/kabum-experiments/kabum-experiments-env/lib/python3.8/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/home/name/contributing/kabum-experiments/kabum-experiments-env/lib/python3.8/site-packages/spacy/util.py", line 472, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'pt_core_news_lg'. It doesn't seem to be a Python package or a valid path to a data directory.`

**Comment by Uss-Momas** [comment]
**solution**
Run on terminal:
`python3 -m spacy download pt_core_news_lg`

**Comment by Uss-Momas** [comment]
**solution**
Run on terminal:
`python3 -m spacy download pt_core_news_lg`
